# Generated by Django 3.2.2 on 2021-05-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(choices=[('', 'Select Make'), ('BENZ', 'Benz'), ('AUDI', 'Audi'), ('BMW', 'BMW'), ('TOYOTA', 'Toyota'), ('SUZUKI', 'Suzuki')], default='', max_length=20)),
                ('name', models.CharField(choices=[('', 'Select Model'), ('one', 'M1'), ('two', 'M2'), ('three', 'M3'), ('four', 'M4'), ('five', 'M5')], default='', max_length=50)),
                ('variant', models.CharField(choices=[('', 'Select Variant'), ('sedan', 'SEDAN'), ('coupe', 'COUPE'), ('sports', 'SPORTS CAR'), ('stationwagon', 'STATION WAGON'), ('hatchback', 'HATCHBACK'), ('convertible', 'CONVERTIBLE'), ('suv', 'SPORT-UTILITY VEHICLE (SUV)'), ('minivan', 'MINIVAN'), ('pickup', ' PICKUP TRUCK')], default='', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='models/static/images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
