# Generated by Django 3.0.5 on 2021-05-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
