# Generated by Django 3.0.5 on 2021-05-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellcar',
            name='city',
        ),
        migrations.RemoveField(
            model_name='sellcar',
            name='state',
        ),
    ]
