# Generated by Django 3.0.5 on 2021-05-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_dealer'),
        ('models', '0002_auto_20210513_1214'),
        ('shop', '0002_auto_20210512_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellcar',
            name='dealer_city',
        ),
        migrations.RemoveField(
            model_name='sellcar',
            name='dealer_state',
        ),
        migrations.RemoveField(
            model_name='sellcar',
            name='name',
        ),
        migrations.AddField(
            model_name='sellcar',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.City'),
        ),
        migrations.AddField(
            model_name='sellcar',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Model'),
        ),
        migrations.AddField(
            model_name='sellcar',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.State'),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Dealer'),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Make'),
        ),
        migrations.AlterField(
            model_name='sellcar',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Variant'),
        ),
    ]
