# Generated by Django 3.0.5 on 2021-05-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20210515_2133'),
        ('home', '0005_dealer'),
        ('shop', '0003_auto_20210513_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellcar',
            name='dealer',
        ),
        migrations.AddField(
            model_name='sellcar',
            name='car_main_Img',
            field=models.ImageField(blank=True, upload_to='shop/'),
        ),
        migrations.CreateModel(
            name='ExchangeCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('year', models.IntegerField()),
                ('kilometer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regno', models.IntegerField()),
                ('expectedprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_main_Img', models.ImageField(blank=True, upload_to='shop/')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.City')),
                ('make', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Make')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Model')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.State')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Variant')),
            ],
        ),
    ]
